### ISSUE TITLE
re-running f5os_ntp_server.py requires key-id to be set

### ISSUE THREAD

**Issue by MVogel91** [F5Networks/f5-ansible-f5os#10]
##### COMPONENT NAME
f5os_ntp_server.py

##### ANSIBLE VERSION

```
# ansible --version
ansible [core 2.17.1]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```
##### F5OS VERSION
```
1.5.2-21056
```
##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

Create NTP servers with address only.
Re-running the same playbook fails for missing key-id.

```
    - name: Create NTP servers
      f5os_ntp_server:
        server: "{{ item.address }}"
      with_items: "{{ env.ntp }}"
```

##### EXPECTED RESULTS

The object being identified as unchanged/ok.

##### ACTUAL RESULTS

```
TASK [Create NTP servers] ******************************************************************************************************************************************************************************************************
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_f5os_ntp_server_payload_cn4q4x4k/ansible_f5os_ntp_server_payload.zip/ansible_collections/f5networks/f5os/plugins/modules/f5os_ntp_server.py", line 147, in compare
AttributeError: 'Difference' object has no attribute 'key_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-local-34727a_1o4bn/ansible-tmp-1719218724.5681655-3710-170074854231225/AnsiballZ_f5os_ntp_server.py", line 107, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-local-34727a_1o4bn/ansible-tmp-1719218724.5681655-3710-170074854231225/AnsiballZ_f5os_ntp_server.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-local-34727a_1o4bn/ansible-tmp-1719218724.5681655-3710-170074854231225/AnsiballZ_f5os_ntp_server.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.f5networks.f5os.plugins.modules.f5os_ntp_server', init_globals=dict(_module_fqn='ansible_collections.f5networks.f5os.plugins.modules.f5os_ntp_server', _modlib_path=modlib_path),
  File "/usr/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_f5os_ntp_server_payload_cn4q4x4k/ansible_f5os_ntp_server_payload.zip/ansible_collections/f5networks/f5os/plugins/modules/f5os_ntp_server.py", line 370, in <module>
  File "/tmp/ansible_f5os_ntp_server_payload_cn4q4x4k/ansible_f5os_ntp_server_payload.zip/ansible_collections/f5networks/f5os/plugins/modules/f5os_ntp_server.py", line 363, in main
  File "/tmp/ansible_f5os_ntp_server_payload_cn4q4x4k/ansible_f5os_ntp_server_payload.zip/ansible_collections/f5networks/f5os/plugins/modules/f5os_ntp_server.py", line 213, in exec_module
  File "/tmp/ansible_f5os_ntp_server_payload_cn4q4x4k/ansible_f5os_ntp_server_payload.zip/ansible_collections/f5networks/f5os/plugins/modules/f5os_ntp_server.py", line 227, in present
  File "/tmp/ansible_f5os_ntp_server_payload_cn4q4x4k/ansible_f5os_ntp_server_payload.zip/ansible_collections/f5networks/f5os/plugins/modules/f5os_ntp_server.py", line 244, in update
  File "/tmp/ansible_f5os_ntp_server_payload_cn4q4x4k/ansible_f5os_ntp_server_payload.zip/ansible_collections/f5networks/f5os/plugins/modules/f5os_ntp_server.py", line 237, in should_update
  File "/tmp/ansible_f5os_ntp_server_payload_cn4q4x4k/ansible_f5os_ntp_server_payload.zip/ansible_collections/f5networks/f5os/plugins/modules/f5os_ntp_server.py", line 185, in _update_changed_options
  File "/tmp/ansible_f5os_ntp_server_payload_cn4q4x4k/ansible_f5os_ntp_server_payload.zip/ansible_collections/f5networks/f5os/plugins/modules/f5os_ntp_server.py", line 150, in compare
  File "/tmp/ansible_f5os_ntp_server_payload_cn4q4x4k/ansible_f5os_ntp_server_payload.zip/ansible_collections/f5networks/f5os/plugins/modules/f5os_ntp_server.py", line 155, in __default
  File "/tmp/ansible_f5os_ntp_server_payload_cn4q4x4k/ansible_f5os_ntp_server_payload.zip/ansible_collections/f5networks/f5os/plugins/modules/f5os_ntp_server.py", line 113, in key_id
KeyError: 'f5-openconfig-system-ntp:key-id'
failed: [10.170.9.37] (item={'address': '1.2.3.4'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "address": "1.2.3.4"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_f5os_ntp_server_payload_cn4q4x4k/ansible_f5os_ntp_server_payload.zip/ansible_collections/f5networks/f5os/plugins/modules/f5os_ntp_server.py\", line 147, in compare\nAttributeError: 'Difference' object has no attribute 'key_id'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-local-34727a_1o4bn/ansible-tmp-1719218724.5681655-3710-170074854231225/AnsiballZ_f5os_ntp_server.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-local-34727a_1o4bn/ansible-tmp-1719218724.5681655-3710-170074854231225/AnsiballZ_f5os_ntp_server.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-local-34727a_1o4bn/ansible-tmp-1719218724.5681655-3710-170074854231225/AnsiballZ_f5os_ntp_server.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.f5networks.f5os.plugins.modules.f5os_ntp_server', init_globals=dict(_module_fqn='ansible_collections.f5networks.f5os.plugins.modules.f5os_ntp_server', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_f5os_ntp_server_payload_cn4q4x4k/ansible_f5os_ntp_server_payload.zip/ansible_collections/f5networks/f5os/plugins/modules/f5os_ntp_server.py\", line 370, in <module>\n  File \"/tmp/ansible_f5os_ntp_server_payload_cn4q4x4k/ansible_f5os_ntp_server_payload.zip/ansible_collections/f5networks/f5os/plugins/modules/f5os_ntp_server.py\", line 363, in main\n  File \"/tmp/ansible_f5os_ntp_server_payload_cn4q4x4k/ansible_f5os_ntp_server_payload.zip/ansible_collections/f5networks/f5os/plugins/modules/f5os_ntp_server.py\", line 213, in exec_module\n  File \"/tmp/ansible_f5os_ntp_server_payload_cn4q4x4k/ansible_f5os_ntp_server_payload.zip/ansible_collections/f5networks/f5os/plugins/modules/f5os_ntp_server.py\", line 227, in present\n  File \"/tmp/ansible_f5os_ntp_server_payload_cn4q4x4k/ansible_f5os_ntp_server_payload.zip/ansible_collections/f5networks/f5os/plugins/modules/f5os_ntp_server.py\", line 244, in update\n  File \"/tmp/ansible_f5os_ntp_server_payload_cn4q4x4k/ansible_f5os_ntp_server_payload.zip/ansible_collections/f5networks/f5os/plugins/modules/f5os_ntp_server.py\", line 237, in should_update\n  File \"/tmp/ansible_f5os_ntp_server_payload_cn4q4x4k/ansible_f5os_ntp_server_payload.zip/ansible_collections/f5networks/f5os/plugins/modules/f5os_ntp_server.py\", line 185, in _update_changed_options\n  File \"/tmp/ansible_f5os_ntp_server_payload_cn4q4x4k/ansible_f5os_ntp_server_payload.zip/ansible_collections/f5networks/f5os/plugins/modules/f5os_ntp_server.py\", line 150, in compare\n  File \"/tmp/ansible_f5os_ntp_server_payload_cn4q4x4k/ansible_f5os_ntp_server_payload.zip/ansible_collections/f5networks/f5os/plugins/modules/f5os_ntp_server.py\", line 155, in __default\n  File \"/tmp/ansible_f5os_ntp_server_payload_cn4q4x4k/ansible_f5os_ntp_server_payload.zip/ansible_collections/f5networks/f5os/plugins/modules/f5os_ntp_server.py\", line 113, in key_id\nKeyError: 'f5-openconfig-system-ntp:key-id'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1603.

**Comment by urohit011** [comment]
This bug has been fixed and should be available in the daily builds
